language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "2.7"

branches:
  only:
    - master
    - tests

env:
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=1.11,<1.12"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django>=2.1,<2.2"

script:
  - coverage run --source=django_netjsongraph runtests.py
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./tests/manage.py makemigrations django_netjsongraph --dry-run; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./tests/manage.py migrate; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./tests/manage.py makemigrations django_netjsongraph --dry-run; fi

after_success:
  coveralls
