language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "2.7"

branches:
  only:
    - master
    - tests

env:
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=1.11,<1.12"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django>=2.1,<2.2"

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./tests/manage.py makemigrations django_netjsongraph --dry-run --verbosity 3; fi

after_success:
  coveralls
