# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsongraph', '0007_link_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='kind',
            field=models.CharField(choices=[(b'normal', 'NORMAL'), (b'block_cut_tree', 'BLOCK_CUT_TREE')], db_index=True, default=(b'normal', 'NORMAL'), max_length=16, verbose_name='kind'),
        ),
    ]
