# Generated by Django 2.1.8 on 2019-05-01 15:55
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('django_netjsongraph', '0008_snapshot_kind'),
    ]
    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='kind',
            field=models.CharField(choices=[('normal', 'NORMAL'), ('block_cut_tree', 'BLOCK_CUT_TREE')], db_index=True, default=('normal', 'NORMAL'), max_length=16, verbose_name='kind'),
        ),
    ]
